from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class Message(BaseModel):
    """Represents a single message in the chat history."""
    role: str = Field(..., description="Role of the sender: 'user' or 'assistant'")
    content: str = Field(..., description="Content of the message")


class AdvisorRequest(BaseModel):
    """Request payload for the advisor endpoint."""
    ml_context: Dict[str, Any] = Field(
        ..., 
        description="Scoring details: probability, top negative contributions, base features, etc."
    )
    chat_history: List[Message] = Field(
        default_factory=list, 
        description="History of the conversation so far."
    )
    user_message: str = Field(
        ..., 
        description="The current question or message from the user."
    )


class AdvisorResponse(BaseModel):
    """Response payload from the advisor endpoint."""
    reply: str = Field(..., description="The advice text generated by the LLM.")
